### ISSUE TITLE
Cannot list or get GCP interconnects using InterconnectsClient() in Python

### ISSUE THREAD

**Issue by rjouhann** [googleapis/python-compute#311]
#### Environment details

```
root@62c3387734ef:~# python3 --version
Python 3.10.4

root@62c3387734ef:~# pip3 --version
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

root@62c3387734ef:~# pip3 show google-cloud-compute
Name: google-cloud-compute
Version: 1.4.0
Summary: 
Home-page: https://github.com/googleapis/python-compute
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: google-api-core, proto-plus, protobuf
Required-by: 
```

#### Steps to reproduce

1. Create an Interconnect in GCP

<img width="1068" alt="Screen Shot 2022-08-01 at 20 05 11" src="https://user-images.githubusercontent.com/25542366/182283327-13011432-584e-4fa0-8ffb-b9d2577b0dc7.png">

2. See the example code below trying to list the interconnects in GCP (see [SDK doc](https://cloud.google.com/python/docs/reference/compute/latest/google.cloud.compute_v1.services.interconnects.InterconnectsClient#google_cloud_compute_v1_services_interconnects_InterconnectsClient_list))

I am able to list instances using a different class, so there isn't any problems with authentication.

#### Code example

```python
import json  # needed to manipulate JSON
import os.path # used to read the credential files and get the project_id
from google.cloud import compute_v1 # GCP SDK
from google.protobuf.json_format import MessageToJson # used to convert GCP output to JSON

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '/root/secret.json'
with open(os.environ['GOOGLE_APPLICATION_CREDENTIALS'], 'r') as fp:
    credentials = json.load(fp)
project_id = credentials['project_id']
print("Project ID: " + project_id)

client = compute_v1.InterconnectsClient()
response = client.list(project=project_id)
print(response)

print("########")

response = client.get(project=project_id, interconnect="demo-pf-capable-moray")
print(response)
```

#### Stack trace
```
root@62c3387734ef:~# python3 debug2.py 
Project ID: prefab-setting-1234567
ListPager<id: "projects/prefab-setting-1234567/global/interconnects"
kind: "compute#interconnectList"
self_link: "https://www.googleapis.com/compute/v1/projects/prefab-setting-1234567/global/interconnects"
>
########
Traceback (most recent call last):
  File "/root/debug2.py", line 16, in <module>
    response = client.get(project=project_id, interconnect="demo-pf-capable-moray")
  File "/usr/local/lib/python3.10/dist-packages/google/cloud/compute_v1/services/interconnects/client.py", line 690, in get
    response = rpc(
  File "/usr/local/lib/python3.10/dist-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/google/api_core/grpc_helpers.py", line 50, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/google/cloud/compute_v1/services/interconnects/transports/rest.py", line 531, in __call__
    raise core_exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 GET https://compute.googleapis.com/compute/v1/projects/prefab-setting-357415/global/interconnects/demo-pf-capable-moray: The resource 'projects/prefab-setting-357415/global/interconnects/demo-pf-capable-moray' was not found
```

**Comment by rjouhann** [comment]
I was using the incorrect function, should have used: `compute_v1.InterconnectAttachmentsClient()`
