### ISSUE TITLE
Script `fixup_compute_v1_keywords.py` has 11 unresolved merge conflicts

### ISSUE THREAD

**Issue by auphofBSF** [googleapis/python-compute#58]
Compile of `python-compute` is failing when trying to compile, my app  is being being built by GoogleCloudPlatform/buildpacks  
```
Failure: (ID: 49c34848) *** Error compiling './.venv/Lib/site-packages/scripts/fixup_compute_v1_keywords.py'...
  File "./.venv/Lib/site-packages/scripts/fixup_compute_v1_keywords.py", line 51
    <<<<<<< HEAD
    ^
SyntaxError: invalid syntax
```

sees attributable to the 1st of 11 merge conflicts that have not been resolved, I am unsure which lines to accept?
https://github.com/googleapis/python-compute/blob/c81bfa752c9db93edd0cd56fec3a79599704d792/scripts/fixup_compute_v1_keywords.py#L51

**Comment by parthea** [comment]
Thanks for reporting this, @auphofBSF ! There was an issue with the merge conflict resolution in #33.

**Comment by parthea** [comment]
@busunkim96 Please can you take a look? I tried to regenerate the client locally but I received the following from the `python3 -m synthtool` command :
```
Use --sandbox_debug to see verbose messages from the sandbox
google/cloud/compute/v1/compute.proto:28:1: warning: Import google/api/resource.proto is unused.
Traceback (most recent call last):
  File "/usr/local/google/home/partheniou/.cache/bazel/_bazel_partheniou/aa81c0a3097a58c95be2c74ab729f8ad/sandbox/linux-sandbox/1308/execroot/com_google_googleapis_discovery/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/cli/generate.py", line 23, in <module>
    from gapic import generator
  File "/usr/local/google/home/partheniou/.cache/bazel/_bazel_partheniou/aa81c0a3097a58c95be2c74ab729f8ad/sandbox/linux-sandbox/1308/execroot/com_google_googleapis_discovery/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/generator/__init__.py", line 21, in <module>
    from .generator import Generator
  File "/usr/local/google/home/partheniou/.cache/bazel/_bazel_partheniou/aa81c0a3097a58c95be2c74ab729f8ad/sandbox/linux-sandbox/1308/execroot/com_google_googleapis_discovery/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/generator/generator.py", line 26, in <module>
    from gapic.samplegen import manifest, samplegen
  File "/usr/local/google/home/partheniou/.cache/bazel/_bazel_partheniou/aa81c0a3097a58c95be2c74ab729f8ad/sandbox/linux-sandbox/1308/execroot/com_google_googleapis_discovery/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/samplegen/__init__.py", line 15, in <module>
    from gapic.samplegen import samplegen
  File "/usr/local/google/home/partheniou/.cache/bazel/_bazel_partheniou/aa81c0a3097a58c95be2c74ab729f8ad/sandbox/linux-sandbox/1308/execroot/com_google_googleapis_discovery/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/samplegen/samplegen.py", line 29, in <module>
    from gapic.schema import api
  File "/usr/local/google/home/partheniou/.cache/bazel/_bazel_partheniou/aa81c0a3097a58c95be2c74ab729f8ad/sandbox/linux-sandbox/1308/execroot/com_google_googleapis_discovery/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/__init__.py", line 23, in <module>
    from gapic.schema.api import API
  File "/usr/local/google/home/partheniou/.cache/bazel/_bazel_partheniou/aa81c0a3097a58c95be2c74ab729f8ad/sandbox/linux-sandbox/1308/execroot/com_google_googleapis_discovery/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/gapic_generator_python/gapic/schema/api.py", line 36, in <module>
    import grpc  # type: ignore
  File "/usr/local/google/home/partheniou/.cache/bazel/_bazel_partheniou/aa81c0a3097a58c95be2c74ab729f8ad/sandbox/linux-sandbox/1308/execroot/com_google_googleapis_discovery/bazel-out/host/bin/external/gapic_generator_python/gapic_plugin.runfiles/com_github_grpc_grpc/src/python/grpcio/grpc/__init__.py", line 23, in <module>
    from grpc._cython import cygrpc as _cygrpc
ImportError: /usr/local/google/home/partheniou/.cache/bazel/_bazel_partheniou/aa81c0a3097a58c95be2c74ab729f8ad/sandbox/linux-sandbox/1308/execroot/com_google_googleapis_discovery/bazel-out/host/bin/external/gap
```
